### PR TITLE
Some optimizations, some fixes to boundary conditions, and some initialization fixes.

### PR DESCRIPTION
**Pull request by searching46dof**
Some issues this should fix:
- yaw insensitivity due to transposing horizontal and vertical focal lengths in PositionSolver camera_matrix 
- insensitivity at short distances less than 1 meter
- yaw and pitch jitter at large angles, affecting each other and also roll
- FOV is no longer required but provides accurate yaw when provided.
- add 1.5x pitch scaling factor due to yaw insensitivity when lack of direct overhead lighting (maybe make this configurable via gui?)
- fix correct_rotation yaw and pitch adjustment when face is not centered in preview window
- add boundary conditions for maximum yaw and pitch preventing unexpected axis flipping or roll 

Optimize:
- MAFilter::filter by keeping a history of the sum for calculating the average
- ImageProcessor::transpose by reducing multiple levels of indirection in nested for loops.
- ImageProcessor::normalize_and_transpose by combining normalize and transpose functionality in the same nested for loops
- Tracker::Tracker configures Ort::SessionOptions to use optimal parallel threads

In PositionSolver::PositionSolver, initialization of camera_matrix is simplified to be more understandable/maintainable.

#ifdef's have been left in place to easily compare differences for now and can be removed later

### CODE REVIEW

**Comment by searching46dof** [comment]
For some reason both AMD uProf and VS CommEd 2022 do not provide profile info in dll's but do provide them for AiTrack,exe. This may be due to being registered callbacks. The #ifdef's are left in place to easily build either for comparison testing.

These changes should provide better stability at larger yaw/pitch. It was tested by reading raw UDP values in opentrack and also via in game use in DCS

**Comment by AIRLegend** [comment]
Awesome! Thank you!  ❤️

Could you please change the base to the **dev** branch and fix the conflicts? The other day I merged another PR with configuration stuff that I think that has minor conflicts with some files.

**Comment by searching46dof** [comment]
fixed an issue where header file should be <string> instead of <stdstring>

**Comment by searching46dof** [comment]
When building Client with VS, have you encountered "there no qt version assigned to this project" (which the properties indicate is version 3.3) ?

**Comment by AIRLegend** [comment]
Yeah, I changed it on the dev branch a couple days ago because I couldn't build the project. Sorry for the inconvenience :/ 

I think you can change the path to your installation via the "Qt project settings" within VS. 

Anyways, I'll change it back to some variable available for everyone when I test/integrate your changes into master.

Merging. Have a nice day :)

**Comment by searching46dof** [comment]
Sorry, I couldn't get to the merge. I needed to take care of some time sensistive stuff. I'm also new to github and still trying to find my way around.
For Client, I compiled the changes externally and then tried merging them. Setting defaults for blank IP address and port should help out of the box first use. I added IPv6 support disabled since I couldn't build Client to test it.
In correct_rotation, I added a pitch boost (scale by 1.5x) for insensitivity due to lack of overhead lighting. So 20degees is scaled to 30degrees and is applicable for most gaming. However, it really should have a GUI checkbox to enable it. There may be cases where it's more important to obtain a more precise pitch angle.

**Comment by AIRLegend** [comment]
Okay. No problem. I'll review it as soon as I can and I'll also add you as reviewer :)

**Pull request merged**
